// ============================================================
// Financial Data Model — Budgeting System
//
// This module defines the canonical, strongly-typed contracts
// for every financial entity the application manages.
//
// General conventions:
//   - All monetary values are plain numbers in the account's
//     `currency` (see PeriodConfig.currency).
//   - All dates are ISO strings: "YYYY-MM-DD".
//   - All month keys are "YYYY-MM" (e.g. "2025-07").
//   - Entity ids are stable, human-readable strings (e.g. "a1",
//     "tx-42") supplied by the seed data or generated by the
//     data store when a new record is created.
// ============================================================

// ------------------------------------------------------------
// Accounts
// ------------------------------------------------------------

export type AccountType =
  | "checking"
  | "savings"
  | "investment"
  | "credit"
  /** Production's real account_type enum also includes this value
   *  (distinct from "credit" — both are liability/debt accounts). See
   *  isDebtAccountType in @/lib/calculations, the single source of truth
   *  for "is this account a debt/liability account" across the app. */
  | "credit_card"
  | "loan"
  /** Production's real account_type enum also includes these three asset
   *  types. See isAssetAccountType in @/lib/calculations, the single
   *  source of truth for "is this account an asset account" across the
   *  app. */
  | "cash"
  | "bank"
  | "mobile_money"
  /** Present in the schema but deliberately unclassified — see
   *  ASSET_ACCOUNT_TYPES's doc comment in @/lib/calculations for why. */
  | "other";

export type CurrencyCode = "USD" | "EUR" | "GBP" | "KES";

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  /** Balance at the start of the active fiscal period. */
  openingBalance: number;
  /** Balance as of the latest transaction in the dataset. */
  currentBalance: number;
  currency: string;
  institution?: string;
  /** Soft-delete flag — inactive accounts are hidden from data entry. */
  active: boolean;
}

// ------------------------------------------------------------
// Transactions
// ------------------------------------------------------------

export type TransactionType = "income" | "expense" | "transfer";

export type TransactionStatus = "pending" | "cleared" | "reconciled";

export interface Transaction {
  id: string;
  date: string; // "YYYY-MM-DD"
  accountId: string;
  categoryId: string;
  type: TransactionType;
  amount: number;
  description: string;
  status: TransactionStatus;
  notes?: string;
  /** Set when this transaction was generated from a planned transaction. */
  plannedId?: string;
  /** Required when type === "transfer" (destination account). */
  toAccountId?: string;
  /**
   * ISO currency code the ORIGINAL amount is denominated in. Absent on
   * legacy records — those default to their account's currency (the
   * pre-existing single-currency dataset), so nothing is ever guessed
   * per transaction and no historical value changes.
   */
  currency?: string;
}

// ------------------------------------------------------------
// Categories
// ------------------------------------------------------------

export type CategoryGroup =
  | "income"
  | "savings"
  | "investments"
  | "bills"
  | "expenses"
  | "debt";

export type CategoryType = "income" | "expense";

export interface Category {
  id: string;
  name: string;
  group: CategoryGroup;
  type: CategoryType;
  color: string;
  /** Optional parent category id for nesting. */
  parentId?: string;
}

// ------------------------------------------------------------
// Budgets
// ------------------------------------------------------------

export interface Budget {
  id: string;
  categoryId: string;
  /** Period this budget belongs to (see PeriodConfig.id, e.g. "2025-2026"). */
  periodId: string;
  /** Month the budget applies to, "YYYY-MM". */
  month: string;
  plannedAmount: number;
  /** Derived from posted transactions where practical. */
  actualAmount: number;
}

// ------------------------------------------------------------
// Goals
// ------------------------------------------------------------

export type GoalStatus =
  | "active"
  | "on-track"
  | "at-risk"
  | "completed"
  | "paused";

export interface Goal {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  targetDate: string; // "YYYY-MM-DD"
  status: GoalStatus;
  /** Currency the target/current amounts are stored in. Legacy goals
   *  default to the app's base currency (USD), never guessed. */
  currency?: string;
}

// ------------------------------------------------------------
// Planned Transactions (recurring / upcoming)
// ------------------------------------------------------------

export type Recurrence = "once" | "monthly" | "yearly";

export type PlannedTransactionStatus = "pending" | "completed" | "cancelled";

export interface PlannedTransaction {
  id: string;
  date: string; // "YYYY-MM-DD"
  accountId: string;
  categoryId: string;
  description: string;
  amount: number;
  type: TransactionType;
  status: PlannedTransactionStatus;
  recurrence?: Recurrence;
  /** Destination account — required when type === "transfer". */
  toAccountId?: string;
  /** Currency the planned amount is stored in. Legacy entries default
   *  to their account's currency, never guessed. */
  currency?: string;
}

// ------------------------------------------------------------
// Period Configuration
// ------------------------------------------------------------

export interface PeriodConfig {
  id: string;
  label: string;
  startDate: string; // "YYYY-MM-DD"
  endDate: string; // "YYYY-MM-DD"
  months: string[]; // ["YYYY-MM", ...] covering the period
  currency: string;
}

// ------------------------------------------------------------
// Supporting types for the data-entry layer
// ------------------------------------------------------------

/** Create a new record of type T by omitting the auto-generated id. */
export type NewEntity<T extends { id: string }> = Omit<T, "id">;

/** Every entity the data store manages. */
export type FinancialEntity =
  | Account
  | Transaction
  | Category
  | Budget
  | Goal
  | PlannedTransaction;

// ------------------------------------------------------------
// Dashboard presentation row types
//
// These are derived, read-only shapes produced by
// app/lib/calculations.ts for the locked dashboard UI.
// They are intentionally NOT the source of truth for data entry.
// ------------------------------------------------------------

export interface DashboardKPI {
  label: string;
  value: string;
  percentage: number;
  color: string;
}

export interface MonthlyBarRow {
  month: string;
  income: number;
  outflow: number;
}

export interface DonutRow {
  name: string;
  value: number;
  color: string;
}

export interface HeaderChartRow {
  month: string;
  value: number;
}

export interface OutflowRow {
  name: string;
  amount: string;
  percentage: number;
}

export interface SpendingRow {
  name: string;
  amount: string;
  percentage: number;
}

export interface TodoRow {
  id: string;
  text: string;
  done: boolean;
}

export interface GoalRow {
  id: string;
  title: string;
  targetAmount: number;
  currentAmount: number;
  deadline: string;
  priority: "high" | "medium" | "low";
}

export interface ProgressRow {
  label: string;
  value: number;
  total: number;
}

// ------------------------------------------------------------
// Activities — day-to-day tracking
//
// A lightweight, optional layer for the Activity tab. Activities
// are associated with a specific calendar date and exist purely
// for personal tracking; they never affect the financial data.
// ------------------------------------------------------------

export type ActivityStatus = "pending" | "in-progress" | "completed";

export type ActivityPriority = "low" | "medium" | "high";

export interface Activity {
  id: string;
  title: string;
  /** The calendar date the activity belongs to ("YYYY-MM-DD"). */
  date: string;
  notes?: string;
  status: ActivityStatus;
  /** Optional due date ("YYYY-MM-DD"). */
  dueDate?: string;
  priority?: ActivityPriority;
  /** ISO timestamp when the activity was marked completed. */
  completedAt?: string;
}

// ------------------------------------------------------------
// Notifications / Reminders
// ------------------------------------------------------------

export type NotificationType = "activity" | "budget" | "recurring" | "goal" | "info";

export type NotificationStatus = "unread" | "read" | "dismissed";

export interface Notification {
  id: string;
  title: string;
  message: string;
  type: NotificationType;
  status: NotificationStatus;
  /** ISO timestamp or date string. */
  date: string;
  actionLabel?: string;
  actionHref?: string;
}

// ------------------------------------------------------------
// Dashboard search & filter
// ------------------------------------------------------------

export interface DashboardFilter {
  search?: string;
  dateFrom?: string;
  dateTo?: string;
  categoryId?: string;
  type?: "income" | "expense" | "all";
  minAmount?: number;
  maxAmount?: number;
  status?: string;
}