-- ============================================================
-- 022_platform_ownership_transfer.sql — SUPERSEDED, DO NOT APPLY
-- ============================================================
--
-- STATUS: This migration was NEVER applied to production and MUST NOT
-- be applied to the current production schema. It is kept in the
-- repository only as a historical record; its executable SQL has been
-- removed so it cannot be mistaken for the current implementation or
-- accidentally run by a future migration tool.
--
-- WHY IT IS SUPERSEDED:
--   1. It targets a `public.audit_events` table that does not exist on
--      the current production database (confirmed live, 2026-09-16).
--      Applying it as written would fail immediately on the
--      `alter table public.audit_events ...` statement.
--   2. It predates the Phase 1 security lockdown
--      (20260915190000_lock_platform_admin_column.sql). That migration
--      added a trigger (profiles_guard_platform_admin) that blocks any
--      authenticated-role change to profiles.is_platform_admin UNLESS a
--      narrow, transaction-local bypass flag is set. This migration's
--      plain UPDATE statements never set that flag, so even a corrected,
--      audit_events-free version of this function would be blocked by
--      the current trigger.
--
-- THE AUTHORITATIVE REPLACEMENT:
--   supabase/migrations/20260916010000_platform_ownership_transfer_rpc.sql
--   This is the migration actually applied to production (verified
--   2026-09-16: function definition matches this repository's copy
--   byte-for-byte; authorization, self-transfer/nonexistent-target
--   rejection, and the Phase 1 trigger bypass are all covered by
--   tests/ownership-transfer.test.ts). It targets the CURRENT schema
--   (no audit_events dependency) and correctly sets the Phase 1 bypass
--   flag before its two UPDATE statements.
--
-- See also: supabase/migrations/README.md for the full picture of how
-- this repository's migration history relates to what is actually
-- deployed to production.
